'use strict';

module.exports = {
  authenticate: require('./authenticate'),
  buildProviderModel: require('./build-provider-model'),
  collectFormErrors: require('./collect-form-errors'),
  exchangeStormpathToken: require('./exchange-stormpath-token'),
  createStormpathSession: require('./create-stormpath-session'),
  createSession: require('./create-session'),
  expandAccount: require('./expand-account'),
  getHost: require('./get-host'),
  getRequiredRegistrationFields: require('./get-required-registration-fields'),
  getAppModuleVersion: require('./get-app-module-version'),
  handleAcceptRequest: require('./handle-accept-request'),
  writeJsonError: require('./write-json-error'),
  writeFormError: require('./write-form-error'),
  loginResponder: require('./login-responder'),
  loginWithOAuthProvider: require('./login-with-oauth-provider'),
  prepAccountData: require('./prep-account-data'),
  render: require('./render'),
  bodyParser: require('./body-parser'),
  sanitizeFormData: require('./sanitize-form-data'),
  setTempCookie: require('./set-temp-cookie'),
  validateAccount: require('./validate-account'),
  xsrfValidator: require('./xsrf-validator'),
  revokeToken: require('./revoke-token'),
  getFormViewModel: require('./get-form-view-model').default,
  strippedAccount: require('./stripped-account-response'),
  requiresOrganizationResolution: require('./requires-organization-resolution'),
  parentDomainRedirect: require('./parent-domain-redirect'),
  isRootDomainMultiTenantRequest: require('./is-root-domain-multi-tenant-request'),
  redirectToOrganization: require('./redirect-to-organization'),
  organizationResolutionGuard: require('./organization-resolution-guard'),
  CachedStore: require('./cached-store'),
  assertOrganizationIsMappedToApplication: require('./assert-org-mapped-to-app')
};
